import Problib.Inference
import Trust.Command

#register_trust_claims allowing [propext, Quot.sound, Classical.choice] claims [
  Problib.Inference.KernelInvariant,
  Problib.Inference.Vanishes,
  Problib.Inference.vanishes_of_le,
  Problib.Inference.PresentedChain,
  Problib.Inference.PresentedChain.stepAt,
  Problib.Inference.PresentedChain.retAt,
  Problib.Inference.PresentedChain.retAt_measurable,
  Problib.Inference.PresentedChain.stepAt_markov,
  Problib.Inference.PresentedChain.point,
  Problib.Inference.PresentedChain.initialLaw,
  Problib.Inference.PresentedChain.stateLaw,
  Problib.Inference.PresentedChain.image,
  Problib.Inference.PresentedChain.outputLaw,
  Problib.Inference.PresentedChain.outputKernel,
  Problib.Inference.PresentedChain.outputKernel_markov,
  Problib.Inference.PresentedChain.outputLaw_eq_bind,
  Problib.Inference.PresentedChain.outputLaw_point,
  Problib.Inference.PresentedChain.ofOutput,
  Problib.Inference.PresentedInvariantConvergent,
  Problib.Inference.projected_chain_converges,
  Problib.Inference.mixed_converges,
  Problib.Inference.initialized_converges,
  Problib.Inference.Lumpable,
  Problib.Inference.Lumpable.outputStepAt,
  Problib.Inference.Lumpable.outputChainLaw,
  Problib.Inference.Lumpable.lumped_iterate,
  Problib.Inference.Lumpable.lifted_output,
  Problib.Inference.Lumpable.lumped_chain_converges,
  Problib.Inference.Lumpable.identity,
  Problib.Inference.kernel_invariant_step,
  Problib.Inference.kernel_invariant_iterate,
  Problib.Inference.kernel_invariant_comp,
  Problib.Inference.kernel_invariant_smul,
  Problib.Inference.DetailedBalance,
  Problib.Inference.detailed_balance_invariant,
  Problib.Inference.stay,
  Problib.Inference.identity_invariant,
  Problib.Inference.identity_stuck,
  Problib.Inference.moveOrStay,
  Problib.Inference.lintegral_move_or_stay,
  Problib.Inference.mhKernel,
  Problib.Inference.lintegral_mh_kernel,
  Problib.Inference.mh_kernel_markov,
  Problib.Inference.repeatFirst,
  Problib.Inference.repeatFirst_measurable,
  Problib.Inference.mh_joint,
  Problib.Inference.mhKernelSFinite,
  Problib.Inference.swap,
  Problib.Inference.mh_detailed_balance,
  Problib.Inference.withDensity_swap,
  Problib.Inference.mh_balanced_detailed_balance,
  Problib.Inference.metropolisAccept,
  Problib.Inference.metropolisAccept_measurable,
  Problib.Inference.metropolisAccept_le_one,
  Problib.Inference.metropolis_event,
  Problib.Inference.metropolis_balance,
  Problib.Inference.metropolis_detailed_balance,
  Problib.Inference.metropolis_invariant,
  Problib.Inference.independence_reversible,
  Problib.Inference.metropolisAccept_eq_one,
  Problib.Inference.metropolisAccept_bound,
  Problib.Inference.independence_minorization
]

#audit_registered_claims

#audit_package [Problib.Inference] allowing [
  propext,
  Quot.sound,
  Classical.choice
]
