import Foundations.Measure.Decomposition
import Trust.Command

#register_trust_claims allowing [propext, Quot.sound, Classical.choice] claims [
  Foundations.Measure.Measure.isZeroInfinitySet_restrict_univ_iff,
  Foundations.Measure.Measure.IsZeroInfinitySet.smul_top,
  Foundations.Measure.Measure.IsZeroInfinitySet.eq_smul_top,
  Foundations.Measure.Measure.IsZeroInfinitySet.reverseSemiproduct,
  Foundations.Measure.Measure.RadonNikodymDerivative.density_ae_le_iff,
  Foundations.Measure.Measure.RadonNikodymDerivative.density_ae_le_one_iff,
  Foundations.Measure.Measure.unitDensity,
  Foundations.Measure.Measure.unitDensity_measurable,
  Foundations.Measure.Measure.unitDensity_reconstruct,
  Foundations.Measure.Measure.exists_unitDensity_iff,
  Foundations.Measure.Measure.unitDensity_ae_mono,
  Foundations.Measure.Measure.unitDensity_ae_all_order,
  Foundations.Measure.Measure.IsZeroInfinitySet.withDensity_restrict_eq_restrict_support,
  Foundations.Measure.Measure.TopZeroInfinitySet.restrict_eq,
  Foundations.Measure.Measure.TopZeroInfinitySet.aeInfinityEq_iff,
  Foundations.Measure.Measure.TopZeroInfinitySet.AEInfinityEq.refl,
  Foundations.Measure.Measure.TopZeroInfinitySet.AEInfinityEq.symm,
  Foundations.Measure.Measure.TopZeroInfinitySet.AEInfinityEq.trans,
  Foundations.Measure.Measure.TopZeroInfinitySet.AEInfinityEq.of_aeEq,
  Foundations.Measure.Measure.TopZeroInfinitySet.AEInfinityEq.iff_aeEq_of_sigmaFinite,
  Foundations.Measure.Measure.withDensity_eq_iff_aeInfinityEq,
  Foundations.Measure.Measure.IsDensity.aeInfinityEq,
  Foundations.Measure.Measure.RadonNikodymDerivative.density_aeInfinityEq,
  Foundations.Measure.Measure.IsZeroInfinitySet.of_null,
  Foundations.Measure.Measure.IsZeroInfinitySet.of_null_difference,
  Foundations.Measure.Measure.IsZeroInfinitySet.withDensity,
  Foundations.Measure.Measure.ZeroInfinityAbsolutelyContinuous.refl,
  Foundations.Measure.Measure.ZeroInfinityAbsolutelyContinuous.trans,
  Foundations.Measure.Measure.ZeroInfinityAbsolutelyContinuous.iff_top_difference,
  Foundations.Measure.Measure.ZeroInfinityAbsolutelyContinuous.iff_absolutelyContinuous_of_sigmaFinite,
  Foundations.Measure.Measure.IsDensity.zeroInfinityAbsolutelyContinuous,
  Foundations.Measure.Measure.IsZeroInfinitySet.null_of_sigmaFinite,
  Foundations.Measure.Measure.IsZeroInfinitySet.restrict,
  Foundations.Measure.Measure.TopZeroInfinitySet.restrict_complement_eq,
  Foundations.Measure.Measure.TopZeroInfinitySet.ofSFinite,
  Foundations.Measure.Measure.TopZeroInfinitySet.sigmaFinite_complement,
  Foundations.Measure.Measure.TopZeroInfinitySet.null_iff_sigmaFinite,
  Foundations.Measure.Measure.exists_radonNikodymDerivative_of_finite,
  Foundations.Measure.Measure.RadonNikodymDerivative.ofFinite,
  Foundations.Measure.Measure.RadonNikodymDerivative.ofSFinite,
  Foundations.Measure.Measure.RadonNikodymDerivative.ofSFiniteReference,
  Foundations.Measure.Measure.RadonNikodymDerivative.nonempty_iff,
  Foundations.Measure.Measure.RadonNikodymDerivative.zeroInfinityAbsolutelyContinuous,
  Foundations.Measure.Measure.Hahn.score_le_supremum,
  Foundations.Measure.Measure.Hahn.score_finite,
  Foundations.Measure.Measure.Hahn.score_complement,
  Foundations.Measure.Measure.Hahn.supremum_finite,
  Foundations.Measure.Measure.Hahn.score_modular,
  Foundations.Measure.Measure.Hahn.defect_inter_le,
  Foundations.Measure.Measure.Hahn.exists_defect_le,
  Foundations.Measure.Measure.Hahn.defect_iInter_le,
  Foundations.Measure.Measure.Hahn.exists_maximizer,
  Foundations.Measure.Measure.HahnDecomposition.complement,
  Foundations.Measure.Measure.exists_hahnDecomposition,
  Foundations.Measure.Measure.HahnDecomposition.ofFinite,
  Foundations.Measure.Measure.exists_positive_dominated_region,
  Foundations.Measure.Measure.TopZeroInfinitySet.equalModuloNull,
  Foundations.Measure.Measure.RadonNikodymDerivative.reconstruct_eq,
  Foundations.Measure.Measure.RadonNikodymDerivative.absolutelyContinuous,
  Foundations.Measure.Measure.RadonNikodymDerivative.density_ae_eq
]

#audit_registered_claims

#audit_package [Foundations.Measure.Decomposition] allowing [
  propext,
  Quot.sound,
  Classical.choice
]
