name = "problib"
defaultTargets = ["Problib"]
testDriver = "TrustTest"

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "Problib"

[[lean_lib]]
name = "Trust"

[[lean_lib]]
name = "TrustTest"
