module

public import Problib.Measure.Space
public import Problib.Real.Extended.Order

set_option autoImplicit false

/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Yury Kudryashov, Kexing Ying

Adapted from Mathlib/MeasureTheory/Constructions/BorelSpace/Basic.lean and
Mathlib/MeasureTheory/Constructions/BorelSpace/Order.lean at commit
15fe1e4eb92a37c66db923a0fa96596d7b504a35.

Tiny uses an explicit sigma algebra generated by strict upper rays. This is
the order presentation of the Borel sigma algebra on extended nonnegative
reals.
-/

namespace Problib.Measure

open Problib.Real

universe u v

@[expose] public def ennrealIoi (threshold : ENNReal) : Set ENNReal :=
  fun value => ENNReal.lt threshold value

@[expose] public def ennrealIic (threshold : ENNReal) : Set ENNReal :=
  fun value => ENNReal.le value threshold

@[expose] public def ennrealIio (threshold : ENNReal) : Set ENNReal :=
  fun value => ENNReal.lt value threshold

@[expose] public def ennrealIci (threshold : ENNReal) : Set ENNReal :=
  fun value => ENNReal.le threshold value

@[expose] public def ennrealSingleton (target : ENNReal) : Set ENNReal :=
  fun value => value = target

@[expose] public def ENNRealBorelGenerator : Set (Set ENNReal) :=
  fun set => ∃ threshold, set = ennrealIoi threshold

/-- The order Borel sigma algebra on extended nonnegative reals. -/
@[expose] public def ennrealBorel : Space ENNReal :=
  Space.generated ENNRealBorelGenerator

public theorem ennrealBorel_generator (threshold : ENNReal) :
    ennrealBorel.Measurable (ennrealIoi threshold) :=
  Space.Generated.basic ⟨threshold, rfl⟩

public theorem ennrealBorel_minimal (target : Space ENNReal)
    (rays : ∀ threshold, target.Measurable (ennrealIoi threshold)) :
    ∀ {set}, ennrealBorel.Measurable set → target.Measurable set := by
  apply Space.generated_minimal target
  rintro set ⟨threshold, rfl⟩
  exact rays threshold

/-- A function is Borel measurable exactly when all strict upper-ray
preimages are measurable. -/
@[expose] public def ENNRealMeasurable {α : Type u} (source : Space α)
    (function : α → ENNReal) : Prop :=
  ∀ threshold, source.Measurable
    (Set.preimage function (ennrealIoi threshold))

namespace ENNRealMeasurable

variable {α : Type u} {β : Type v} {source : Space α}
  {target : Space β} {function : α → ENNReal}

public theorem measurableMap (measurable : ENNRealMeasurable source function) :
    MeasurableMap source ennrealBorel function := by
  apply MeasurableMap.into_generated
  rintro set ⟨threshold, rfl⟩
  exact measurable threshold

public theorem of_measurableMap
    (measurable : MeasurableMap source ennrealBorel function) :
    ENNRealMeasurable source function := by
  intro threshold
  exact measurable (ennrealBorel_generator threshold)

public theorem measurableMap_iff :
    MeasurableMap source ennrealBorel function ↔
      ENNRealMeasurable source function :=
  ⟨of_measurableMap, measurableMap⟩

public theorem ioi (measurable : ENNRealMeasurable source function)
    (threshold : ENNReal) :
    source.Measurable (Set.preimage function (ennrealIoi threshold)) :=
  measurable threshold

public theorem constant (source : Space α) (value : ENNReal) :
    ENNRealMeasurable source (fun _ => value) := by
  intro threshold
  classical
  by_cases member : ENNReal.lt threshold value
  · have equal : Set.preimage (fun _ : α => value) (ennrealIoi threshold) =
        Set.univ := by
      apply Set.ext
      intro input
      exact ⟨fun _ => True.intro, fun _ => member⟩
    rw [equal]
    exact source.univ
  · have equal : Set.preimage (fun _ : α => value) (ennrealIoi threshold) =
        Set.empty := by
      apply Set.ext
      intro input
      exact ⟨fun present => False.elim (member present), False.elim⟩
    rw [equal]
    exact source.empty

public theorem identity :
    ENNRealMeasurable ennrealBorel (fun value => value) := by
  intro threshold
  exact ennrealBorel_generator threshold

public theorem comp {map : β → ENNReal} {before : α → β}
    (mapMeasurable : ENNRealMeasurable target map)
    (beforeMeasurable : MeasurableMap source target before) :
    ENNRealMeasurable source (fun value => map (before value)) := by
  intro threshold
  exact beforeMeasurable (mapMeasurable threshold)

end ENNRealMeasurable

@[expose] public noncomputable def ennrealPiecewise {α : Type u}
    (region : Set α) (inside outside : α → ENNReal) : α → ENNReal := by
  classical
  exact fun value => if region value then inside value else outside value

@[expose] public noncomputable def ennrealIndicator {α : Type u}
    (region : Set α) (function : α → ENNReal) : α → ENNReal :=
  ennrealPiecewise region function (fun _ => ENNReal.zero)

namespace ENNRealMeasurable

variable {α : Type u} {source : Space α}
  {function outside : α → ENNReal} {region : Set α}

public theorem piecewise (regionMeasurable : source.Measurable region)
    (insideMeasurable : ENNRealMeasurable source function)
    (outsideMeasurable : ENNRealMeasurable source outside) :
    ENNRealMeasurable source
      (ennrealPiecewise region function outside) := by
  intro threshold
  have unionMeasurable := source.union
    (source.inter regionMeasurable (insideMeasurable threshold))
    (source.inter (source.complement regionMeasurable)
      (outsideMeasurable threshold))
  have equal : Set.preimage
      (ennrealPiecewise region function outside) (ennrealIoi threshold) =
      Set.union
        (Set.inter region (Set.preimage function (ennrealIoi threshold)))
        (Set.inter (Set.complement region)
          (Set.preimage outside (ennrealIoi threshold))) := by
    classical
    apply Set.ext
    intro value
    by_cases member : region value
    · unfold Set.preimage ennrealIoi Set.union Set.inter Set.complement
      unfold ennrealPiecewise
      simp [member]
    · unfold Set.preimage ennrealIoi Set.union Set.inter Set.complement
      unfold ennrealPiecewise
      simp [member]
  rw [equal]
  exact unionMeasurable

public theorem indicator (regionMeasurable : source.Measurable region)
    (functionMeasurable : ENNRealMeasurable source function) :
    ENNRealMeasurable source (ennrealIndicator region function) :=
  piecewise regionMeasurable functionMeasurable
    (constant source ENNReal.zero)

end ENNRealMeasurable

end Problib.Measure
