module

public import Problib.Measure.Space

set_option autoImplicit false

namespace Problib.Measure.Space

universe u v w x

variable {ι : Type u} {α : ι → Type v} {β : Type w}

public section

/-- Cylinder base set generator for the product sigma-algebra.
A generator is the preimage of a measurable coordinate set under single-coordinate projection. -/
@[expose] def PiGenerator (spaces : ∀ index, Space (α index)) :
    Set (Set (∀ index, α index)) :=
  fun region => ∃ index, ∃ coordinate,
    (spaces index).Measurable coordinate ∧
      region = Set.preimage (fun point => point index) coordinate

/-- Dependent product measurable space for arbitrary index types.
It is generated by single-coordinate cylinder sets. -/
@[expose] def pi (spaces : ∀ index, Space (α index)) : Space (∀ index, α index) :=
  generated (PiGenerator spaces)

/-- Coordinate projection from the product measurable space is measurable. -/
theorem coordinate_measurable (spaces : ∀ index, Space (α index)) (index : ι) :
    MeasurableMap (pi spaces) (spaces index) (fun point => point index) := by
  intro region measurable
  exact Generated.basic ⟨index, region, measurable, rfl⟩

/-- A function into a product measurable space is measurable whenever every
coordinate projection is measurable. -/
theorem pi_measurable {source : Space β} {spaces : ∀ index, Space (α index)}
    {function : β → ∀ index, α index}
    (measurable : ∀ index, MeasurableMap source (spaces index) (fun input => function input index)) :
    MeasurableMap source (pi spaces) function := by
  apply MeasurableMap.into_generated
  rintro region ⟨index, coordinate, coordinateMeasurable, rfl⟩
  exact measurable index coordinateMeasurable

/-- A function into a product measurable space is measurable if and only if
each coordinate projection is measurable. -/
theorem pi_measurable_iff {source : Space β} {spaces : ∀ index, Space (α index)}
    {function : β → ∀ index, α index} :
    MeasurableMap source (pi spaces) function ↔
      ∀ index, MeasurableMap source (spaces index) (fun input => function input index) :=
  ⟨fun measurable index => MeasurableMap.comp (coordinate_measurable spaces index) measurable,
    pi_measurable⟩

/-- Product map between product spaces from a family of coordinate
measurable maps. -/
theorem pi_map {γ : ι → Type x} {sources : ∀ index, Space (α index)}
    {targets : ∀ index, Space (γ index)} {functions : ∀ index, α index → γ index}
    (measurable : ∀ index, MeasurableMap (sources index) (targets index) (functions index)) :
    MeasurableMap (pi sources) (pi targets) (fun point index => functions index (point index)) :=
  pi_measurable (fun index =>
    MeasurableMap.comp (measurable index) (coordinate_measurable sources index))

/-- Reindexing map between product measurable spaces is measurable. -/
theorem pi_reindex {κ : Type x} (spaces : ∀ index, Space (α index)) (indices : κ → ι) :
    MeasurableMap (pi spaces) (pi (fun index => spaces (indices index)))
      (fun point index => point (indices index)) :=
  pi_measurable (fun index => coordinate_measurable spaces (indices index))

end

end Problib.Measure.Space
