module

public import Problib.Measure.Dynkin.Basic

set_option autoImplicit false

/-
Copyright (c) 2021 Martin Zinkevich. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Martin Zinkevich, Rémy Degenne

Adapted from Mathlib/MeasureTheory/PiSystem.lean at commit
15fe1e4eb92a37c66db923a0fa96596d7b504a35.

Tiny uses unconditional intersection closure in `PiSystem`.
-/

namespace Problib.Measure

universe u

variable {α : Type u}

public section

namespace DynkinSystem

theorem generated_measurable {generators : Set (Set α)} {set : Set α}
    (contains : (generated generators).Contains set) :
    (Space.generated generators).Measurable set :=
  generated_minimal (ofSpace (Space.generated generators))
    (fun generatorMember => Space.generated_contains generatorMember) contains

/-- The Dynkin system generated by a pi-system is closed under binary
intersection. -/
theorem generated_intersection {generators : Set (Set α)}
    (pi : PiSystem generators) {left right : Set α}
    (leftContains : (generated generators).Contains left)
    (rightContains : (generated generators).Contains right) :
    (generated generators).Contains (Set.inter left right) := by
  have generatorsIntersectRight : ∀ {generator}, generators generator →
      (generated generators).Contains (Set.inter generator right) := by
    intro generator generatorMember
    have generatorContains :
        (generated generators).Contains generator :=
      generated_contains generatorMember
    have allIntersectGenerator : ∀ {set},
        (generated generators).Contains set →
        (restrictOn (generated generators) generatorContains).Contains set :=
      generated_minimal
        (restrictOn (generated generators) generatorContains) (by
          intro other otherMember
          exact generated_contains (pi otherMember generatorMember))
    have rightIntersectsGenerator := allIntersectGenerator rightContains
    change (generated generators).Contains
      (Set.inter right generator) at rightIntersectsGenerator
    rw [Set.inter_comm] at rightIntersectsGenerator
    exact rightIntersectsGenerator
  have allIntersectRight : ∀ {set},
      (generated generators).Contains set →
      (restrictOn (generated generators) rightContains).Contains set :=
    generated_minimal (restrictOn (generated generators) rightContains)
      generatorsIntersectRight
  exact allIntersectRight leftContains

/-- Dynkin's pi-lambda theorem. A pi-system has the same measurable and
Dynkin closures. -/
theorem pi_lambda {generators : Set (Set α)} (pi : PiSystem generators)
    {set : Set α} :
    (Space.generated generators).Measurable set ↔
      (generated generators).Contains set := by
  constructor
  · intro measurable
    exact Space.generated_minimal
      (toSpace (generated generators)
        (fun leftContains rightContains =>
          generated_intersection pi leftContains rightContains))
      (fun generatorMember => generated_contains generatorMember) measurable
  · exact generated_measurable

end DynkinSystem

end

end Problib.Measure
