module

public import Problib.Measure.Real.Borel
public import Problib.Measure.Dynkin.Basic
public import Problib.Measure.Space.Generator
import Problib.Real.Basis

set_option autoImplicit false

namespace Problib.Measure.Real

open Problib.Real
open Problib.Real.Construction

public section

/-- Countable generator for the Borel σ-algebra on the real line consisting of rational
open lower rays `(-∞, q)`. -/
noncomputable def countableGenerator : Space.CountableGenerator borel where
  sets := fun index => Iio (Dedekind.rationalBasis index)
  generated := by
    classical
    let generated := Space.generated (fun set => ∃ index, Iio (Dedekind.rationalBasis index) = set)
    have rays (upper : Carrier) : generated.Measurable (Iio upper) := by
      let sets : Nat → Set Carrier := fun index =>
        if Dedekind.lt (Dedekind.rationalBasis index) upper then
          Iio (Dedekind.rationalBasis index) else Set.empty
      have equal : Iio upper = Set.iUnion sets := by
        apply Set.ext
        intro value
        constructor
        · intro below
          rcases Dedekind.exists_rationalBasis_between below with ⟨index, above, less⟩
          exact ⟨index, by simpa only [sets, if_pos less, Iio] using above⟩
        · rintro ⟨index, member⟩
          by_cases below : Dedekind.lt (Dedekind.rationalBasis index) upper
          · simp only [sets, if_pos below] at member
            exact Dedekind.lt_trans member below
          · simp only [sets, if_neg below] at member
            exact False.elim member
      rw [equal]
      apply generated.iUnion
      intro index
      by_cases below : Dedekind.lt (Dedekind.rationalBasis index) upper
      · simp only [sets, if_pos below]
        exact Space.generated_contains ⟨index, rfl⟩
      · simp only [sets, if_neg below]
        exact generated.empty
    have identity : MeasurableMap generated borel (fun value => value) :=
      measurableMap_borel_iff_iio.mpr rays
    apply Space.ext
    intro region
    constructor
    · exact identity
    · apply Space.generated_minimal borel
      rintro set ⟨index, rfl⟩
      exact measurable_iio _

/-- Countable generator for the Borel σ-algebra on the unit interval obtained by
pulling back rational rays along unit inclusion. -/
noncomputable def unitCountableGenerator : Space.CountableGenerator unitBorel :=
  countableGenerator.comap unitInclusion

/-- The family of closed initial intervals `[0, point]` in the unit interval. -/
@[expose] def unitInitials : Set (Set UnitInterval) :=
  fun set => ∃ point, set = unitInitial point

/-- Preimages of initial rays under unit inclusion are generated by initial
intervals. -/
theorem generated_initials_iic (upper : Carrier) :
    (Space.generated unitInitials).Measurable
      (Set.preimage unitInclusion (Iic upper)) := by
  classical
  by_cases nonnegative : Dedekind.le Dedekind.zero upper
  · by_cases bounded : Dedekind.le upper Dedekind.one
    · exact Space.generated_contains ⟨⟨upper, nonnegative, bounded⟩, rfl⟩
    · have upperOne : Dedekind.le Dedekind.one upper :=
        (not_le_iff_lt.mp bounded).1
      have same : Set.preimage unitInclusion (Iic upper) = Set.univ := by
        apply Set.ext
        intro value
        exact ⟨fun _ => True.intro, fun _ => Dedekind.le_trans value.property.2 upperOne⟩
      rw [same]
      exact (Space.generated unitInitials).univ
  · have same : Set.preimage unitInclusion (Iic upper) = Set.empty := by
      apply Set.ext
      intro value
      exact ⟨fun member => nonnegative (Dedekind.le_trans value.property.1 member), False.elim⟩
    rw [same]
    exact (Space.generated unitInitials).empty

/-- Initial closed intervals generate the Borel σ-algebra on the unit
interval. -/
theorem unitBorel_generated_initials :
    unitBorel = Space.generated unitInitials := by
  apply Space.ext
  intro set
  constructor
  · apply Space.comap_minimal
    apply MeasurableMap.into_generated
    rintro basic ⟨lower, upper, rfl⟩
    rw [ioc_eq_difference]
    exact (Space.generated unitInitials).difference
      (generated_initials_iic upper) (generated_initials_iic lower)
  · exact Space.generated_minimal unitBorel (fun {_} ⟨point, same⟩ => same ▸ unitInitial_measurable point)

/-- The family of initial closed intervals is closed under binary
intersection. -/
theorem unitInitials_pi : PiSystem unitInitials := by
  rintro left right ⟨leftPoint, rfl⟩ ⟨rightPoint, rfl⟩
  rcases Dedekind.le_total leftPoint.val rightPoint.val with leftBefore | rightBefore
  · refine ⟨leftPoint, ?_⟩
    apply Set.ext
    intro value
    exact ⟨fun both => both.1, fun member => ⟨member, Dedekind.le_trans member leftBefore⟩⟩
  · refine ⟨rightPoint, ?_⟩
    apply Set.ext
    intro value
    exact ⟨fun both => both.2, fun member => ⟨Dedekind.le_trans member rightBefore, member⟩⟩

/-- The entire unit interval belongs to the initial-interval family
at `point = 1`. -/
theorem unitInitials_univ : unitInitials Set.univ := by
  refine ⟨unitOne, ?_⟩
  apply Set.ext
  intro value
  exact ⟨fun _ => value.property.2, fun _ => True.intro⟩

end

end Problib.Measure.Real
