module

public import Problib.Measure.Additive.Core
public import Problib.Measure.Null.Basic
public import Problib.Measure.Real.Borel
public import Problib.Measure.Real.Cover

set_option autoImplicit false

/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Copyright (c) 2021 Sébastien Gouëzel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Sébastien Gouëzel, Yury Kudryashov

Adapted from Mathlib/MeasureTheory/Measure/Lebesgue/Basic.lean and
Mathlib/MeasureTheory/Measure/Stieltjes.lean at commit
15fe1e4eb92a37c66db923a0fa96596d7b504a35.

Tiny constructs volume from countable half-open interval covers and restricts
the resulting outer measure to its explicit Borel space.
-/

namespace Problib.Measure.Real

open Problib.Real
open Problib.Real.Construction

/-- The outer measure generated by exact lengths of half-open intervals. -/
@[expose] public noncomputable def lebesgueOuter : OuterMeasure Carrier :=
  OuterMeasure.ofFunction intervalCost intervalCost_empty

public theorem lebesgueOuter_isCaratheodory_ioi (boundary : Carrier) :
    lebesgueOuter.IsCaratheodory (Ioi boundary) := by
  unfold lebesgueOuter
  apply OuterMeasure.ofFunction_caratheodory
  intro set
  exact intervalCost_split_ioi set boundary

public theorem lebesgueOuter_isCaratheodory_iic (boundary : Carrier) :
    lebesgueOuter.IsCaratheodory (Iic boundary) := by
  rw [← complement_ioi]
  exact lebesgueOuter.isCaratheodory_complement
    (lebesgueOuter_isCaratheodory_ioi boundary)

public theorem lebesgueOuter_isCaratheodory_ioc
    (lower upper : Carrier) :
    lebesgueOuter.IsCaratheodory (Ioc lower upper) := by
  rw [ioc_eq_inter]
  exact lebesgueOuter.isCaratheodory_inter
    (lebesgueOuter_isCaratheodory_ioi lower)
    (lebesgueOuter_isCaratheodory_iic upper)

public theorem lebesgueOuter_isCaratheodory_of_borel
    {set : Set Carrier} (measurable : borel.Measurable set) :
    lebesgueOuter.IsCaratheodory set := by
  apply Space.generated_minimal lebesgueOuter.caratheodory
    (fun {set} member => ?_) measurable
  rcases member with ⟨lower, upper, rfl⟩
  exact lebesgueOuter_isCaratheodory_ioc lower upper

/-- Lebesgue volume on the selected real carrier. -/
@[expose] public noncomputable def volume : Measure borel :=
  lebesgueOuter.toMeasure fun _ measurable =>
    lebesgueOuter_isCaratheodory_of_borel measurable

public theorem volume_apply {set : Set Carrier}
    (measurable : borel.Measurable set) :
    volume set = lebesgueOuter set := by
  unfold volume
  exact OuterMeasure.toMeasure_apply lebesgueOuter
    (fun _ setMeasurable =>
      lebesgueOuter_isCaratheodory_of_borel setMeasurable)
    measurable

public theorem lebesgueOuter_ioc (lower upper : Carrier) :
    lebesgueOuter (Ioc lower upper) =
      ENNReal.ofReal (Dedekind.sub upper lower) := by
  apply ENNReal.le_antisymm
  · exact ENNReal.le_trans
      (OuterMeasure.ofFunction_le intervalCost intervalCost_empty
        (Ioc lower upper))
      (by rw [intervalCost_ioc]; exact ENNReal.le_refl _)
  · unfold lebesgueOuter
    apply OuterMeasure.le_ofFunction_apply intervalCost intervalCost_empty
    intro cover
    exact intervalLength_le_coverCost cover

/-- A half-open interval has its exact endpoint difference as volume. -/
@[simp] public theorem volume_ioc (lower upper : Carrier) :
    volume (Ioc lower upper) =
      ENNReal.ofReal (Dedekind.sub upper lower) := by
  rw [volume_apply (measurable_ioc lower upper)]
  exact lebesgueOuter_ioc lower upper

private theorem icc_self (point : Carrier) :
    Icc point point = Set.singleton point := by
  apply Set.ext
  intro value
  constructor
  · intro member
    exact Dedekind.le_antisymm member.2 member.1
  · intro equal
    subst value
    exact ⟨Dedekind.le_refl point, Dedekind.le_refl point⟩

public theorem measurable_singleton (point : Carrier) :
    borel.Measurable (Set.singleton point) := by
  rw [← icc_self]
  exact measurable_icc point point

private theorem sub_lt_self_of_positive {value shift : Carrier}
    (positive : Dedekind.lt Dedekind.zero shift) :
    Dedekind.lt (Dedekind.sub value shift) value := by
  have translated := (Dedekind.add_lt_add_left_iff
    (left := Dedekind.zero) (right := shift)
    (shift := Dedekind.sub value shift)).mpr positive
  simpa only [Dedekind.add_zero,
    Dedekind.add_comm (Dedekind.sub value shift) shift,
    Dedekind.add_sub_cancel value shift] using translated

/-- Every singleton has zero Lebesgue volume. -/
@[simp] public theorem volume_singleton (point : Carrier) :
    volume (Set.singleton point) = ENNReal.zero := by
  apply ENNReal.le_antisymm
  · apply ENNReal.le_of_forall_positive_le_add
    intro error errorPositive
    cases error with
    | top =>
        rw [ENNReal.add_top]
        exact ENNReal.le_top _
    | finite errorValue =>
        change NNReal.lt NNReal.zero errorValue at errorPositive
        let width := NNReal.toReal errorValue
        have widthPositive : Dedekind.lt Dedekind.zero width :=
          errorPositive
        have included : Set.Subset (Set.singleton point)
            (Ioc (Dedekind.sub point width) point) := by
          intro value equal
          subst value
          exact ⟨sub_lt_self_of_positive widthPositive,
            Dedekind.le_refl point⟩
        have bound := volume.mono included
        have widthConversion :
            ENNReal.ofReal width = ENNReal.finite errorValue := by
          unfold width
          exact ENNReal.ofReal_toReal_finite errorValue
        rw [volume_ioc, Dedekind.sub_sub_cancel, widthConversion] at bound
        simpa only [ENNReal.zero_add] using bound
  · exact ENNReal.zero_le _

/-- Lebesgue volume of an arbitrary closed interval `[lower, upper]`.
Because `ENNReal.ofReal` maps nonpositive values to zero, reversed intervals
with `upper ≤ lower` evaluate to zero volume. -/
@[simp] public theorem volume_icc (lower upper : Carrier) :
    volume (Icc lower upper) = ENNReal.ofReal (Dedekind.sub upper lower) := by
  have same : volume (Icc lower upper) = volume (Ioc lower upper) := by
    apply Measure.measure_eq_of_null_difference
    · apply Measure.NullSet.mono
        (show volume.NullSet (Set.singleton lower) from volume_singleton lower)
      intro value member
      have notStrict : ¬Dedekind.lt lower value :=
        fun strict => member.2 ⟨strict, member.1.2⟩
      exact Dedekind.le_antisymm (not_lt_iff_le.mp notStrict) member.1.1
    · apply volume.null_empty.mono
      intro value member
      exact member.2 ⟨member.1.1.1, member.1.2⟩
  exact same.trans (volume_ioc lower upper)

/-- The closed unit interval has Lebesgue volume one. -/
@[simp] public theorem volume_icc_zero_one :
    volume unitSet = ENNReal.one := by
  rw [show unitSet = Icc Dedekind.zero Dedekind.one from rfl,
    volume_icc, Dedekind.sub_eq_add_neg, Dedekind.neg_zero, Dedekind.add_zero]
  exact ENNReal.ofReal_toReal_finite NNReal.one

end Problib.Measure.Real
