import Foundations.Measure.Giry
import Foundations.Measure.Giry.Necessity
import Trust.Command

#register_trust_claims allowing [propext, Quot.sound, Classical.choice] claims [
  Foundations.Measure.Giry.Law,
  Foundations.Measure.Giry.generators,
  Foundations.Measure.Giry.space,
  Foundations.Measure.Giry.ext,
  Foundations.Measure.Giry.evaluation,
  Foundations.Measure.Giry.measurable_iff,
  Foundations.Measure.Giry.integral_swap,
  Foundations.Measure.Giry.bind_comm,
  Foundations.Measure.Giry.product,
  Foundations.Measure.Giry.product_measurable,
  Foundations.Measure.Giry.product_measure,
  Foundations.Measure.Giry.product_apply,
  Foundations.Measure.Giry.product_swap,
  Foundations.Measure.Giry.ofKernel,
  Foundations.Measure.Giry.ofKernel_measurable,
  Foundations.Measure.Giry.toKernel,
  Foundations.Measure.Giry.toKernel_probability,
  Foundations.Measure.Giry.toKernel_finite,
  Foundations.Measure.Giry.evaluationKernel,
  Foundations.Measure.Giry.toKernel_ofKernel,
  Foundations.Measure.Giry.ofKernel_toKernel,
  Foundations.Measure.Giry.representation_iff,
  Foundations.Measure.Giry.pure,
  Foundations.Measure.Giry.pure_measurable,
  Foundations.Measure.Giry.map,
  Foundations.Measure.Giry.map_measurable,
  Foundations.Measure.Giry.bind,
  Foundations.Measure.Giry.bind_measurable,
  Foundations.Measure.Giry.pure_bind,
  Foundations.Measure.Giry.bind_pure,
  Foundations.Measure.Giry.bind_assoc,
  Foundations.Measure.Giry.join,
  Foundations.Measure.Giry.join_measurable,
  Foundations.Measure.Giry.nonempty_iff,
  Foundations.Measure.Giry.map_id,
  Foundations.Measure.Giry.map_comp,
  Foundations.Measure.Giry.map_pure,
  Foundations.Measure.Giry.bind_apply,
  Foundations.Measure.Giry.lintegral_bind,
  Foundations.Measure.Giry.lintegral_measurable,
  Foundations.Measure.Giry.bind_const,
  Foundations.Measure.Giry.bind_pure_comp,
  Foundations.Measure.Giry.bind_map,
  Foundations.Measure.Giry.map_bind,
  Foundations.Measure.Giry.toKernel_pure,
  Foundations.Measure.Giry.toKernel_bind,
  Foundations.Measure.Giry.bind_eq_join_map,
  Foundations.Measure.Giry.join_pure,
  Foundations.Measure.Giry.join_map_pure,
  Foundations.Measure.Giry.join_assoc,
  Foundations.Measure.Giry.join_map,
  Foundations.Measure.Giry.Necessity.pointLaws,
  Foundations.Measure.Giry.Necessity.pointLaws_not_measurable,
  Foundations.Measure.Giry.Necessity.probability_fibers_do_not_imply_measurability,
  Foundations.Measure.Giry.bind_joint_measurable,
  Foundations.Measure.Giry.bind_family_measurable,
  Foundations.Measure.Giry.strength,
  Foundations.Measure.Giry.strength_measurable,
  Foundations.Measure.Giry.strength_pure,
  Foundations.Measure.Giry.strength_natural,
  Foundations.Measure.Giry.strength_second,
  Foundations.Measure.Giry.strength_unit,
  Foundations.Measure.Giry.strength_associate,
  Foundations.Measure.Giry.strength_bind,
  Foundations.Measure.Giry.strength_join
]

#audit_registered_claims

#audit_package [Foundations.Measure.Giry] allowing [
  propext,
  Quot.sound,
  Classical.choice
]
