import Foundations.Measure.Additive.Finite
import Foundations.Measure.Extended.Basic

set_option autoImplicit false

namespace Foundations.Measure.Giry

open Foundations.Real

universe u v w x

/-- Probability laws on an arbitrary measurable space, defined as a subtype
of countably additive measures with total mass one. -/
def Law {α : Type u} (target : Space α) :=
  { measure : Measure target // Measure.IsProbability measure }

/-- Generating cylinder sets of strict upper rays of measurable-event
evaluations into `ENNReal`. Upper-ray generation follows the local `ENNReal`
measurable presentation. -/
def generators {α : Type u} (target : Space α) : Set (Set (Law target)) :=
  fun event => ∃ region, target.Measurable region ∧ ∃ threshold : ENNReal,
    event = fun law => ENNReal.lt threshold (law.val region)

/-- The measurable space of probability laws on `target`, equipped with the
sigma-algebra generated by evaluation upper rays. -/
def space {α : Type u} (target : Space α) : Space (Law target) :=
  Space.generated (generators target)

variable {α : Type u} {β : Type v} {γ : Type w} {δ : Type x}
  {source : Space α} {target : Space β} {result : Space γ}

/-- Probability law extensionality: two probability laws that agree on all
measurable regions are equal. -/
theorem ext {left right : Law source}
    (equal : ∀ region, source.Measurable region → left.val region = right.val region) :
    left = right :=
  Subtype.ext (Measure.ext equal)

/-- Evaluation of a fixed measurable target region across laws is an
`ENNReal`-measurable function. -/
theorem evaluation {region : Set β} (measurable : target.Measurable region) :
    ENNRealMeasurable (space target) (fun law => law.val region) := by
  intro threshold
  exact Space.Generated.basic ⟨region, measurable, threshold, rfl⟩

/-- Universal measurability criterion: a parameter-indexed family of laws is
measurable into `space target` if and only if evaluating every measurable
region is `ENNReal`-measurable on the parameter space. -/
theorem measurable_iff (family : α → Law target) :
    MeasurableMap source (space target) family ↔
      ∀ {region}, target.Measurable region →
        ENNRealMeasurable source (fun input => (family input).val region) := by
  constructor
  · intro measurable region regionMeasurable
    exact ENNRealMeasurable.comp (evaluation regionMeasurable) measurable
  · intro measurable
    apply MeasurableMap.intoGenerated
    rintro event ⟨region, regionMeasurable, threshold, rfl⟩
    exact measurable regionMeasurable threshold

end Foundations.Measure.Giry
