import Problib.Measure.Kernel.Iteration
import Problib.Measure.Kernel.Iteration.Minorization.Axioms
import Problib.Measure.Kernel.Iteration.Finite.Axioms
import Trust.Command

#register_trust_claims allowing [propext, Quot.sound, Classical.choice] claims [
  Problib.Measure.Kernel.le,
  Problib.Measure.Kernel.le_antisymm,
  Problib.Measure.Kernel.comp_le_comp_right,
  Problib.Measure.Kernel.comp_le_comp_left,
  Problib.Measure.Kernel.comp_add_distrib,
  Problib.Measure.Kernel.add_comp_distrib,
  Problib.Measure.Kernel.comp_sum_right,
  Problib.Measure.Kernel.comp_sum_left,
  Problib.Measure.Kernel.sum_split_head,
  Problib.Measure.Kernel.iterate,
  Problib.Measure.Kernel.iterate_succ_right,
  Problib.Measure.Kernel.loop,
  Problib.Measure.Kernel.prefixApproximant,
  Problib.Measure.Kernel.stepApproximant,
  Problib.Measure.Kernel.prefixApproximant_step_unfold,
  Problib.Measure.Kernel.prefixApproximant_eq_stepApproximant,
  Problib.Measure.Kernel.prefixApproximant_apply_measurable,
  Problib.Measure.Kernel.prefixApproximant_monotone,
  Problib.Measure.Kernel.prefixApproximant_le_loop,
  Problib.Measure.Kernel.loop_eq_iSup_prefixApproximant,
  Problib.Measure.Kernel.loop_unfold,
  Problib.Measure.Kernel.loop_least,
  Problib.Measure.Kernel.IsSFinite.iterate,
  Problib.Measure.Kernel.IsSFinite.loop,
  Problib.Measure.Kernel.prefixApproximant_zero_exit,
  Problib.Measure.Kernel.boundedLoop,
  Problib.Measure.Kernel.boundedLoop_apply,
  Problib.Measure.Kernel.boundedLoop_exhausted,
  Problib.Measure.Kernel.boundedLoop_succeeded,
  Problib.Measure.Kernel.boundedLoop_zero,
  Problib.Measure.Kernel.boundedLoop_zero_exit,
  Problib.Measure.Kernel.boundedLoop_succ,
  Problib.Measure.Kernel.boundedLoop_isProbability,
  Problib.Measure.Kernel.loop_zero_exit,
  Problib.Measure.Kernel.loop_immediate_exit,
  Problib.Measure.Kernel.iterate_zero_step_succ,
  Problib.Measure.Kernel.iterate_identity,
  Problib.Measure.Kernel.pure_continuation_fixed,
  Problib.Measure.Kernel.prefix_mass_recurrence,
  Problib.Measure.Kernel.prefix_mass_le_one,
  Problib.Measure.Kernel.prefix_mass_eq_one,
  Problib.Measure.Kernel.loop_mass_le_one,
  Problib.Measure.Kernel.loop_isFinite,
  Problib.Measure.Kernel.substochastic_isFinite,
  Problib.Measure.Kernel.iterate_mass_antitone,
  Problib.Measure.Kernel.loop_mass_eq_one_sub_iInf,
  Problib.Measure.Kernel.loop_mass_add_iInf_eq_one,
  Problib.Measure.Kernel.loop_mass_one_iff,
  Problib.Measure.Kernel.VanishingContinuation,
  Problib.Measure.Kernel.loop_mass_one_everywhere_iff,
  Problib.Measure.Kernel.loop_isProbability,
  Problib.Measure.Kernel.Lumps,
  Problib.Measure.Kernel.iterate_map_of_lumps,
  Problib.Measure.Kernel.continueOutside,
  Problib.Measure.Kernel.exitInside,
  Problib.Measure.Kernel.stayOutside,
  Problib.Measure.Kernel.hitKernel,
  Problib.Measure.Kernel.survival,
  Problib.Measure.Kernel.HitsAlmostSurely,
  Problib.Measure.Kernel.exitInside_add_stayOutside,
  Problib.Measure.Kernel.stayOutside_comp,
  Problib.Measure.Kernel.continueOutside_congr,
  Problib.Measure.Kernel.hitting_conservative,
  Problib.Measure.Kernel.hit_mass_add_survival,
  Problib.Measure.Kernel.hit_mass_eq_one_iff_survival_vanishes,
  Problib.Measure.Kernel.hitsAlmostSurely_iff,
  Problib.Measure.Kernel.hitsAlmostSurely_of_mem,
  Problib.Measure.Kernel.hitKernel_unfold,
  Problib.Measure.Kernel.hitKernel_concentrated,
  Problib.Measure.Kernel.survival_succ,
  Problib.Measure.Kernel.entrance_peel,
  Problib.Measure.Kernel.hit_positive_iff_reaches,
  Problib.Measure.Kernel.MeasureIrreducible,
  Problib.Measure.Kernel.MeasureIrreducible.mono,
  Problib.Measure.Kernel.MeasureIrreducible.reaches_from,
  Problib.Measure.Kernel.HarrisRecurrent,
  Problib.Measure.Kernel.PositiveHarris,
  Problib.Measure.Kernel.HarrisRecurrent.measureIrreducible,
  Problib.Measure.Kernel.invariant_hits_of_reaches,
  Problib.Measure.Kernel.invariant_hits_almost_everywhere,
  Problib.Measure.Kernel.MeasureCycle,
  Problib.Measure.Kernel.MeasureAperiodic,
  Problib.Measure.Kernel.MeasureCycle.iterate_advance,
  Problib.Measure.Kernel.ConvergesFromEveryLaw,
  Problib.Measure.Kernel.ConvergesFromEveryLaw.invariant,
  Problib.Measure.Kernel.ConvergesFromEveryLaw.invariant_unique,
  Problib.Measure.Kernel.measureAperiodic_of_converges,
  Problib.Measure.Kernel.minorization_convergesFromEveryLaw,
  Problib.Measure.Kernel.Iteration.Necessity.zero_pair_substochastic,
  Problib.Measure.Kernel.Iteration.Necessity.zero_pair_not_conservative,
  Problib.Measure.Kernel.Iteration.Necessity.vanishing_continuation_without_output,
  Problib.Measure.Kernel.Iteration.Necessity.unfolding_does_not_determine_output,
  Problib.Measure.Kernel.OmegaContinuous,
  Problib.Measure.Kernel.OmegaContinuous.linear,
  Problib.Measure.Kernel.fixedPointApproximant,
  Problib.Measure.Kernel.fixedPointApproximant_monotone,
  Problib.Measure.Kernel.leastFixedPoint,
  Problib.Measure.Kernel.leastFixedPoint_apply_measurable,
  Problib.Measure.Kernel.leastFixedPoint_unfold,
  Problib.Measure.Kernel.leastFixedPoint_least,
  Problib.Measure.Kernel.leastFixedPoint_linear_eq_loop,
  Problib.Measure.Kernel.IsSFinite.leastFixedPointOfPrefixSum,
  Problib.Measure.Kernel.SFiniteKernel,
  Problib.Measure.Kernel.PrefixContinuous,
  Problib.Measure.Kernel.PrefixContinuous.witness_independent,
  Problib.Measure.Kernel.PrefixContinuous.congr_kernel,
  Problib.Measure.Kernel.SFiniteKernel.zero,
  Problib.Measure.Kernel.SFiniteKernel.prefixSum,
  Problib.Measure.Kernel.attach_le,
  Problib.Measure.Kernel.attach_congr_kernel,
  Problib.Measure.Kernel.attach_prefixSum,
  Problib.Measure.Kernel.attach_iSupIncreasing,
  Problib.Measure.Kernel.precomp_le,
  Problib.Measure.Kernel.precomp_iSupIncreasing,
  Problib.Measure.Kernel.precomp_prefixSum,
  Problib.Measure.Kernel.copair_prefixSum,
  Problib.Measure.Kernel.SFiniteKernel.linear,
  Problib.Measure.Kernel.SFiniteKernel.linear_monotone,
  Problib.Measure.Kernel.PrefixContinuous.linear,
  Problib.Measure.Kernel.CausalPrefixOperator,
  Problib.Measure.Kernel.CausalPrefixMap,
  Problib.Measure.Kernel.CausalPrefixMap.toOperator,
  Problib.Measure.Kernel.CausalPrefixMap.toContinuous,
  Problib.Measure.Kernel.CausalPrefixMap.constant,
  Problib.Measure.Kernel.CausalPrefixMap.identity,
  Problib.Measure.Kernel.CausalPrefixMap.compose,
  Problib.Measure.Kernel.CausalPrefixMap.attach,
  Problib.Measure.Kernel.CausalPrefixMap.map,
  Problib.Measure.Kernel.CausalPrefixMap.precomp,
  Problib.Measure.Kernel.CausalPrefixMap.copair,
  Problib.Measure.Kernel.SFiniteKernel.linearAction,
  Problib.Measure.Kernel.CausalPrefixOperator.linear,
  Problib.Measure.Kernel.CausalPrefixOperator.fixedIncrements,
  Problib.Measure.Kernel.CausalPrefixOperator.fixedIncrements_eq_action,
  Problib.Measure.Kernel.CausalPrefixOperator.approximant_eq_prefixSum,
  Problib.Measure.Kernel.sfiniteFixedPointApproximant,
  Problib.Measure.Kernel.sfiniteFixedPointApproximant_monotone,
  Problib.Measure.Kernel.sfiniteLeastFixedPoint,
  Problib.Measure.Kernel.sfiniteLeastFixedPoint_unfold,
  Problib.Measure.Kernel.sfiniteLeastFixedPoint_least,
  Problib.Measure.Kernel.sfiniteLeastFixedPoint_eq_leastFixedPoint,
  Problib.Measure.Kernel.SFiniteKernel.linearLeast,
  Problib.Measure.Kernel.SFiniteKernel.linearLeast_eq_loop
]

#audit_registered_claims

#audit_package [Problib.Measure.Kernel.Iteration] allowing [
  propext,
  Quot.sound,
  Classical.choice
]

#print axioms Problib.Measure.Kernel.loop_unfold
#print axioms Problib.Measure.Kernel.loop_least
#print axioms Problib.Measure.Kernel.IsSFinite.loop
#print axioms Problib.Measure.Kernel.prefix_mass_le_one
#print axioms Problib.Measure.Kernel.prefix_mass_eq_one
#print axioms Problib.Measure.Kernel.loop_mass_one_iff
#print axioms Problib.Measure.Kernel.Iteration.Necessity.vanishing_continuation_without_output
#print axioms Problib.Measure.Kernel.Iteration.Necessity.unfolding_does_not_determine_output
