import Problib.Measure.Giry
import Problib.Measure.Giry.Necessity
import Trust.Command

#register_trust_claims allowing [propext, Quot.sound, Classical.choice] claims [
  Problib.Measure.Giry.unitInterval_standardBorel,
  Problib.Measure.Giry.standardBorel,
  Problib.Measure.Giry.Necessity.empty_law_space_standardBorel,
  Problib.Measure.Giry.Necessity.empty_law_space_empty,
  Problib.Measure.Giry.Law,
  Problib.Measure.Giry.generators,
  Problib.Measure.Giry.space,
  Problib.Measure.Giry.ext,
  Problib.Measure.Giry.evaluation,
  Problib.Measure.Giry.measurable_iff,
  Problib.Measure.Giry.integral_swap,
  Problib.Measure.Giry.bind_comm,
  Problib.Measure.Giry.product,
  Problib.Measure.Giry.product_measurable,
  Problib.Measure.Giry.product_measure,
  Problib.Measure.Giry.product_apply,
  Problib.Measure.Giry.product_swap,
  Problib.Measure.Giry.ofKernel,
  Problib.Measure.Giry.ofKernel_measurable,
  Problib.Measure.Giry.toKernel,
  Problib.Measure.Giry.toKernel_probability,
  Problib.Measure.Giry.toKernel_finite,
  Problib.Measure.Giry.evaluationKernel,
  Problib.Measure.Giry.toKernel_ofKernel,
  Problib.Measure.Giry.ofKernel_toKernel,
  Problib.Measure.Giry.representation_iff,
  Problib.Measure.Giry.pure,
  Problib.Measure.Giry.pure_measurable,
  Problib.Measure.Giry.map,
  Problib.Measure.Giry.map_measurable,
  Problib.Measure.Giry.bind,
  Problib.Measure.Giry.bind_measurable,
  Problib.Measure.Giry.pure_bind,
  Problib.Measure.Giry.bind_pure,
  Problib.Measure.Giry.bind_assoc,
  Problib.Measure.Giry.join,
  Problib.Measure.Giry.join_measurable,
  Problib.Measure.Giry.nonempty_iff,
  Problib.Measure.Giry.map_id,
  Problib.Measure.Giry.map_comp,
  Problib.Measure.Giry.map_pure,
  Problib.Measure.Giry.bind_apply,
  Problib.Measure.Giry.lintegral_bind,
  Problib.Measure.Giry.lintegral_measurable,
  Problib.Measure.Giry.bind_const,
  Problib.Measure.Giry.bind_pure_comp,
  Problib.Measure.Giry.bind_map,
  Problib.Measure.Giry.map_bind,
  Problib.Measure.Giry.toKernel_pure,
  Problib.Measure.Giry.toKernel_bind,
  Problib.Measure.Giry.bind_eq_join_map,
  Problib.Measure.Giry.join_pure,
  Problib.Measure.Giry.join_map_pure,
  Problib.Measure.Giry.join_assoc,
  Problib.Measure.Giry.join_map,
  Problib.Measure.Giry.Necessity.pointLaws,
  Problib.Measure.Giry.Necessity.pointLaws_not_measurable,
  Problib.Measure.Giry.Necessity.probability_fibers_do_not_imply_measurability,
  Problib.Measure.Giry.bind_joint_measurable,
  Problib.Measure.Giry.bind_family_measurable,
  Problib.Measure.Giry.strength,
  Problib.Measure.Giry.strength_measurable,
  Problib.Measure.Giry.strength_pure,
  Problib.Measure.Giry.strength_natural,
  Problib.Measure.Giry.strength_second,
  Problib.Measure.Giry.strength_unit,
  Problib.Measure.Giry.strength_associate,
  Problib.Measure.Giry.strength_bind,
  Problib.Measure.Giry.strength_join
]

#audit_registered_claims

#audit_package [Problib.Measure.Giry] allowing [
  propext,
  Quot.sound,
  Classical.choice
]
