module

public import Foundations.Measure.Real.Borel
public import Foundations.Measure.Dynkin.Basic

set_option autoImplicit false

namespace Foundations.Measure.Real

open Foundations.Real
open Foundations.Real.Construction

public section

/-- The family of closed initial intervals `[0, point]` in the unit interval. -/
@[expose] def unitInitials : Set (Set UnitInterval) :=
  fun set => ∃ point, set = unitInitial point

/-- Preimages of initial rays under unit inclusion are generated by initial
intervals. -/
theorem generatedInitials_Iic (upper : Carrier) :
    (Space.generated unitInitials).Measurable
      (Set.preimage unitInclusion (Iic upper)) := by
  classical
  by_cases nonnegative : Dedekind.le Dedekind.zero upper
  · by_cases bounded : Dedekind.le upper Dedekind.one
    · exact Space.generated_contains ⟨⟨upper, nonnegative, bounded⟩, rfl⟩
    · have upperOne : Dedekind.le Dedekind.one upper :=
        (notLeIffLt.mp bounded).1
      have same : Set.preimage unitInclusion (Iic upper) = Set.univ := by
        apply Set.ext
        intro value
        exact ⟨fun _ => True.intro, fun _ => Dedekind.leTrans value.property.2 upperOne⟩
      rw [same]
      exact (Space.generated unitInitials).univ
  · have same : Set.preimage unitInclusion (Iic upper) = Set.empty := by
      apply Set.ext
      intro value
      exact ⟨fun member => nonnegative (Dedekind.leTrans value.property.1 member), False.elim⟩
    rw [same]
    exact (Space.generated unitInitials).empty

/-- Initial closed intervals generate the Borel σ-algebra on the unit
interval. -/
theorem unitBorel_generatedInitials :
    unitBorel = Space.generated unitInitials := by
  apply Space.ext
  intro set
  constructor
  · apply Space.comap_minimal
    apply MeasurableMap.intoGenerated
    rintro basic ⟨lower, upper, rfl⟩
    rw [Ioc_eq_difference]
    exact (Space.generated unitInitials).difference
      (generatedInitials_Iic upper) (generatedInitials_Iic lower)
  · exact Space.generated_minimal unitBorel (fun {_} ⟨point, same⟩ => same ▸ unitInitialMeasurable point)

/-- The family of initial closed intervals is closed under binary
intersection. -/
theorem unitInitials_pi : PiSystem unitInitials := by
  rintro left right ⟨leftPoint, rfl⟩ ⟨rightPoint, rfl⟩
  rcases Dedekind.leTotal leftPoint.val rightPoint.val with leftBefore | rightBefore
  · refine ⟨leftPoint, ?_⟩
    apply Set.ext
    intro value
    exact ⟨fun both => both.1, fun member => ⟨member, Dedekind.leTrans member leftBefore⟩⟩
  · refine ⟨rightPoint, ?_⟩
    apply Set.ext
    intro value
    exact ⟨fun both => both.2, fun member => ⟨Dedekind.leTrans member rightBefore, member⟩⟩

/-- The entire unit interval belongs to the initial-interval family
at `point = 1`. -/
theorem unitInitials_univ : unitInitials Set.univ := by
  refine ⟨unitOne, ?_⟩
  apply Set.ext
  intro value
  exact ⟨fun _ => value.property.2, fun _ => True.intro⟩

end

end Foundations.Measure.Real
