module

public import Foundations.Measure.Additive.Core
public import Foundations.Measure.Null.Basic
public import Foundations.Measure.Real.Borel
public import Foundations.Measure.Real.Cover

set_option autoImplicit false

/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Copyright (c) 2021 Sébastien Gouëzel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Sébastien Gouëzel, Yury Kudryashov

Adapted from Mathlib/MeasureTheory/Measure/Lebesgue/Basic.lean and
Mathlib/MeasureTheory/Measure/Stieltjes.lean at commit
15fe1e4eb92a37c66db923a0fa96596d7b504a35.

Tiny constructs volume from countable half-open interval covers and restricts
the resulting outer measure to its explicit Borel space.
-/

namespace Foundations.Measure.Real

open Foundations.Real
open Foundations.Real.Construction

/-- The outer measure generated by exact lengths of half-open intervals. -/
@[expose] public noncomputable def lebesgueOuter : OuterMeasure Carrier :=
  OuterMeasure.ofFunction intervalCost intervalCost_empty

public theorem lebesgueOuter_isCaratheodory_Ioi (boundary : Carrier) :
    lebesgueOuter.IsCaratheodory (Ioi boundary) := by
  unfold lebesgueOuter
  apply OuterMeasure.ofFunction_caratheodory
  intro set
  exact intervalCost_split_Ioi set boundary

public theorem lebesgueOuter_isCaratheodory_Iic (boundary : Carrier) :
    lebesgueOuter.IsCaratheodory (Iic boundary) := by
  rw [← complementIoi]
  exact lebesgueOuter.isCaratheodory_complement
    (lebesgueOuter_isCaratheodory_Ioi boundary)

public theorem lebesgueOuter_isCaratheodory_Ioc
    (lower upper : Carrier) :
    lebesgueOuter.IsCaratheodory (Ioc lower upper) := by
  rw [Ioc_eq_inter]
  exact lebesgueOuter.isCaratheodory_inter
    (lebesgueOuter_isCaratheodory_Ioi lower)
    (lebesgueOuter_isCaratheodory_Iic upper)

public theorem lebesgueOuter_isCaratheodory_of_borel
    {set : Set Carrier} (measurable : borel.Measurable set) :
    lebesgueOuter.IsCaratheodory set := by
  apply Space.generated_minimal lebesgueOuter.caratheodory
    (fun {set} member => ?_) measurable
  rcases member with ⟨lower, upper, rfl⟩
  exact lebesgueOuter_isCaratheodory_Ioc lower upper

/-- Lebesgue volume on the selected real carrier. -/
@[expose] public noncomputable def volume : Measure borel :=
  lebesgueOuter.toMeasure fun _ measurable =>
    lebesgueOuter_isCaratheodory_of_borel measurable

public theorem volume_apply {set : Set Carrier}
    (measurable : borel.Measurable set) :
    volume set = lebesgueOuter set := by
  unfold volume
  exact OuterMeasure.toMeasure_apply lebesgueOuter
    (fun _ setMeasurable =>
      lebesgueOuter_isCaratheodory_of_borel setMeasurable)
    measurable

public theorem lebesgueOuter_Ioc (lower upper : Carrier) :
    lebesgueOuter (Ioc lower upper) =
      ENNReal.ofReal (Dedekind.sub upper lower) := by
  apply ENNReal.leAntisymm
  · exact ENNReal.leTrans
      (OuterMeasure.ofFunction_le intervalCost intervalCost_empty
        (Ioc lower upper))
      (by rw [intervalCost_Ioc]; exact ENNReal.leRefl _)
  · unfold lebesgueOuter
    apply OuterMeasure.le_ofFunction_apply intervalCost intervalCost_empty
    intro cover
    exact intervalLength_le_coverCost cover

/-- A half-open interval has its exact endpoint difference as volume. -/
@[simp] public theorem volume_Ioc (lower upper : Carrier) :
    volume (Ioc lower upper) =
      ENNReal.ofReal (Dedekind.sub upper lower) := by
  rw [volume_apply (measurable_Ioc lower upper)]
  exact lebesgueOuter_Ioc lower upper

private theorem Icc_self (point : Carrier) :
    Icc point point = Set.singleton point := by
  apply Set.ext
  intro value
  constructor
  · intro member
    exact Dedekind.leAntisymm member.2 member.1
  · intro equal
    subst value
    exact ⟨Dedekind.leRefl point, Dedekind.leRefl point⟩

public theorem measurable_singleton (point : Carrier) :
    borel.Measurable (Set.singleton point) := by
  rw [← Icc_self]
  exact measurable_Icc point point

private theorem negAddDistrib (left right : Carrier) :
    Dedekind.neg (Dedekind.add left right) =
      Dedekind.add (Dedekind.neg left) (Dedekind.neg right) := by
  exact Foundations.Algebra.AdditiveCommutativeGroupLaws.negAddDistrib
    Dedekind.additive.group left right

private theorem subSubSelf (value shift : Carrier) :
    Dedekind.sub value (Dedekind.sub value shift) = shift := by
  rw [Dedekind.subEqAddNeg, Dedekind.subEqAddNeg, negAddDistrib,
    Dedekind.negNeg]
  calc
    Dedekind.add value
        (Dedekind.add (Dedekind.neg value) shift) =
        Dedekind.add
          (Dedekind.add value (Dedekind.neg value)) shift :=
      (Dedekind.addAssoc value (Dedekind.neg value) shift).symm
    _ = Dedekind.add Dedekind.zero shift := by rw [Dedekind.addNeg]
    _ = shift :=
      Foundations.Algebra.AdditiveCommutativeGroupLaws.zeroAdd
        Dedekind.additive.group shift

private theorem sub_lt_self_of_positive {value shift : Carrier}
    (positive : Dedekind.lt Dedekind.zero shift) :
    Dedekind.lt (Dedekind.sub value shift) value := by
  have translated := (Dedekind.addLtAddLeftIff
    (left := Dedekind.zero) (right := shift)
    (shift := Dedekind.sub value shift)).mpr positive
  simpa only [Dedekind.addZero,
    Dedekind.addComm (Dedekind.sub value shift) shift,
    addSubCancel value shift] using translated

/-- Every singleton has zero Lebesgue volume. -/
@[simp] public theorem volume_singleton (point : Carrier) :
    volume (Set.singleton point) = ENNReal.zero := by
  apply ENNReal.leAntisymm
  · apply ENNReal.leOfForallPositiveLeAdd
    intro error errorPositive
    cases error with
    | top =>
        rw [ENNReal.addTop]
        exact ENNReal.leTop _
    | finite errorValue =>
        change NNReal.lt NNReal.zero errorValue at errorPositive
        let width := NNReal.toReal errorValue
        have widthPositive : Dedekind.lt Dedekind.zero width :=
          errorPositive
        have included : Set.Subset (Set.singleton point)
            (Ioc (Dedekind.sub point width) point) := by
          intro value equal
          subst value
          exact ⟨sub_lt_self_of_positive widthPositive,
            Dedekind.leRefl point⟩
        have bound := volume.mono included
        have widthConversion :
            ENNReal.ofReal width = ENNReal.finite errorValue := by
          unfold width
          exact ENNReal.ofRealToRealFinite errorValue
        rw [volume_Ioc, subSubSelf, widthConversion] at bound
        simpa only [ENNReal.zeroAdd] using bound
  · exact ENNReal.zeroLe _

/-- Lebesgue volume of an arbitrary closed interval `[lower, upper]`.
Because `ENNReal.ofReal` maps nonpositive values to zero, reversed intervals
with `upper ≤ lower` evaluate to zero volume. -/
@[simp] public theorem volume_Icc (lower upper : Carrier) :
    volume (Icc lower upper) = ENNReal.ofReal (Dedekind.sub upper lower) := by
  have same : volume (Icc lower upper) = volume (Ioc lower upper) := by
    apply Measure.measure_eq_of_null_difference
    · apply Measure.NullSet.mono
        (show volume.NullSet (Set.singleton lower) from volume_singleton lower)
      intro value member
      have notStrict : ¬Dedekind.lt lower value :=
        fun strict => member.2 ⟨strict, member.1.2⟩
      exact Dedekind.leAntisymm (notLtIffLe.mp notStrict) member.1.1
    · apply volume.null_empty.mono
      intro value member
      exact member.2 ⟨member.1.1.1, member.1.2⟩
  exact same.trans (volume_Ioc lower upper)

/-- The closed unit interval has Lebesgue volume one. -/
@[simp] public theorem volume_Icc_zero_one :
    volume unitSet = ENNReal.one := by
  rw [show unitSet = Icc Dedekind.zero Dedekind.one from rfl,
    volume_Icc, Dedekind.subEqAddNeg, Dedekind.negZero, Dedekind.addZero]
  exact ENNReal.ofRealToRealFinite NNReal.one

end Foundations.Measure.Real
