module

public import Foundations.QuasiBorel.Pi
public import Foundations.QuasiBorel.Measurable.Hom
public import Foundations.Measure.Pi

set_option autoImplicit false

namespace Foundations.QuasiBorel

open Foundations.Measure

universe u v w

variable {Ω : Type u} {ι : Type v} {alpha : ι → Type w}

public section

/-- Canonical quasi-Borel morphism from the quasi-Borel product of measurable
spaces to the space generated by the product measurable space. -/
@[expose] def Space.piToMeasurable (source : Foundations.Measure.Space Ω)
    (spaces : ∀ index, Foundations.Measure.Space (alpha index)) :
    Hom (Space.pi (fun index => Space.ofMeasurable source (spaces index)))
      (Space.ofMeasurable source (Foundations.Measure.Space.pi spaces)) where
  toFun := fun point => point
  mapRandom := by
    intro random accepted
    exact Foundations.Measure.Space.pi_measurable accepted

/-- Canonical quasi-Borel morphism from the space generated by the product
measurable space to the quasi-Borel product of measurable spaces. -/
@[expose] def Space.piOfMeasurable (source : Foundations.Measure.Space Ω)
    (spaces : ∀ index, Foundations.Measure.Space (alpha index)) :
    Hom (Space.ofMeasurable source (Foundations.Measure.Space.pi spaces))
      (Space.pi (fun index => Space.ofMeasurable source (spaces index))) where
  toFun := fun point => point
  mapRandom := by
    intro random accepted index
    exact MeasurableMap.comp (Foundations.Measure.Space.coordinate_measurable spaces index) accepted

/-- Left inverse identity proving R(Meas) preserves arbitrary products over any
measurable random source. -/
theorem Space.piToMeasurable_piOfMeasurable (source : Foundations.Measure.Space Ω)
    (spaces : ∀ index, Foundations.Measure.Space (alpha index)) :
    Hom.comp (Space.piToMeasurable source spaces) (Space.piOfMeasurable source spaces) =
      Hom.identity (Space.ofMeasurable source (Foundations.Measure.Space.pi spaces)) := by
  apply Hom.ext
  intro point
  rfl

/-- Right inverse identity proving R(Meas) preserves arbitrary products over
any measurable random source. -/
theorem Space.piOfMeasurable_piToMeasurable (source : Foundations.Measure.Space Ω)
    (spaces : ∀ index, Foundations.Measure.Space (alpha index)) :
    Hom.comp (Space.piOfMeasurable source spaces) (Space.piToMeasurable source spaces) =
      Hom.identity (Space.pi (fun index => Space.ofMeasurable source (spaces index))) := by
  apply Hom.ext
  intro point
  rfl

end

end Foundations.QuasiBorel
